### PR TITLE
Change forgotten lines of apt to nala

### PR DESCRIPTION
**Pull request by win20-official**

### CODE REVIEW

**Comment by nxjosephofficial** [comment]
Hello. Using nala is nice idea!

If the user wants to continue with nala, I think we can use `.bashrc` for this.

```
echo 'apt() {
  command nala "$@"
}
sudo() {
  if [ "$1" = "apt" ]; then
    shift
    command sudo nala "$@"
  else
    command sudo "$@"
  fi
}' >> ~/.bashrc

```
```
echo 'apt() { 
  command nala "$@"
}
sudo() {
  if [ "$1" = "apt" ]; then
    shift
    command sudo nala "$@"
  else
    command sudo "$@"
  fi
}' | sudo tee -a /root/.bashrc
```

**Comment by win20-official** [comment]
But what if you want to use apt

**Comment by win20-official** [comment]
You know i forgot some lines so that's why i made this update

**Comment by nxjosephofficial** [comment]
> You know i forgot some lines so that's why i made this update

I know, my comments are about using nala in general.

> But what if you want to use apt

I just said if user wants to continue with nala.

**Pull request merged**
